
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Drawing` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Drawing
 * 
 */
export type DrawingModel = runtime.Types.Result.DefaultSelection<Prisma.$DrawingPayload>

export type AggregateDrawing = {
  _count: DrawingCountAggregateOutputType | null
  _min: DrawingMinAggregateOutputType | null
  _max: DrawingMaxAggregateOutputType | null
}

export type DrawingMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  filename: string | null
  fileType: string | null
  filePath: string | null
  status: string | null
  createdAt: Date | null
}

export type DrawingMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  filename: string | null
  fileType: string | null
  filePath: string | null
  status: string | null
  createdAt: Date | null
}

export type DrawingCountAggregateOutputType = {
  id: number
  projectId: number
  filename: number
  fileType: number
  filePath: number
  status: number
  createdAt: number
  _all: number
}


export type DrawingMinAggregateInputType = {
  id?: true
  projectId?: true
  filename?: true
  fileType?: true
  filePath?: true
  status?: true
  createdAt?: true
}

export type DrawingMaxAggregateInputType = {
  id?: true
  projectId?: true
  filename?: true
  fileType?: true
  filePath?: true
  status?: true
  createdAt?: true
}

export type DrawingCountAggregateInputType = {
  id?: true
  projectId?: true
  filename?: true
  fileType?: true
  filePath?: true
  status?: true
  createdAt?: true
  _all?: true
}

export type DrawingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Drawing to aggregate.
   */
  where?: Prisma.DrawingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drawings to fetch.
   */
  orderBy?: Prisma.DrawingOrderByWithRelationInput | Prisma.DrawingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DrawingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drawings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drawings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Drawings
  **/
  _count?: true | DrawingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DrawingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DrawingMaxAggregateInputType
}

export type GetDrawingAggregateType<T extends DrawingAggregateArgs> = {
      [P in keyof T & keyof AggregateDrawing]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDrawing[P]>
    : Prisma.GetScalarType<T[P], AggregateDrawing[P]>
}




export type DrawingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DrawingWhereInput
  orderBy?: Prisma.DrawingOrderByWithAggregationInput | Prisma.DrawingOrderByWithAggregationInput[]
  by: Prisma.DrawingScalarFieldEnum[] | Prisma.DrawingScalarFieldEnum
  having?: Prisma.DrawingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DrawingCountAggregateInputType | true
  _min?: DrawingMinAggregateInputType
  _max?: DrawingMaxAggregateInputType
}

export type DrawingGroupByOutputType = {
  id: string
  projectId: string
  filename: string
  fileType: string
  filePath: string
  status: string
  createdAt: Date
  _count: DrawingCountAggregateOutputType | null
  _min: DrawingMinAggregateOutputType | null
  _max: DrawingMaxAggregateOutputType | null
}

type GetDrawingGroupByPayload<T extends DrawingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DrawingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DrawingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DrawingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DrawingGroupByOutputType[P]>
      }
    >
  >



export type DrawingWhereInput = {
  AND?: Prisma.DrawingWhereInput | Prisma.DrawingWhereInput[]
  OR?: Prisma.DrawingWhereInput[]
  NOT?: Prisma.DrawingWhereInput | Prisma.DrawingWhereInput[]
  id?: Prisma.StringFilter<"Drawing"> | string
  projectId?: Prisma.StringFilter<"Drawing"> | string
  filename?: Prisma.StringFilter<"Drawing"> | string
  fileType?: Prisma.StringFilter<"Drawing"> | string
  filePath?: Prisma.StringFilter<"Drawing"> | string
  status?: Prisma.StringFilter<"Drawing"> | string
  createdAt?: Prisma.DateTimeFilter<"Drawing"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  extractedData?: Prisma.ExtractedDataListRelationFilter
}

export type DrawingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  extractedData?: Prisma.ExtractedDataOrderByRelationAggregateInput
}

export type DrawingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DrawingWhereInput | Prisma.DrawingWhereInput[]
  OR?: Prisma.DrawingWhereInput[]
  NOT?: Prisma.DrawingWhereInput | Prisma.DrawingWhereInput[]
  projectId?: Prisma.StringFilter<"Drawing"> | string
  filename?: Prisma.StringFilter<"Drawing"> | string
  fileType?: Prisma.StringFilter<"Drawing"> | string
  filePath?: Prisma.StringFilter<"Drawing"> | string
  status?: Prisma.StringFilter<"Drawing"> | string
  createdAt?: Prisma.DateTimeFilter<"Drawing"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  extractedData?: Prisma.ExtractedDataListRelationFilter
}, "id">

export type DrawingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.DrawingCountOrderByAggregateInput
  _max?: Prisma.DrawingMaxOrderByAggregateInput
  _min?: Prisma.DrawingMinOrderByAggregateInput
}

export type DrawingScalarWhereWithAggregatesInput = {
  AND?: Prisma.DrawingScalarWhereWithAggregatesInput | Prisma.DrawingScalarWhereWithAggregatesInput[]
  OR?: Prisma.DrawingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DrawingScalarWhereWithAggregatesInput | Prisma.DrawingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Drawing"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Drawing"> | string
  filename?: Prisma.StringWithAggregatesFilter<"Drawing"> | string
  fileType?: Prisma.StringWithAggregatesFilter<"Drawing"> | string
  filePath?: Prisma.StringWithAggregatesFilter<"Drawing"> | string
  status?: Prisma.StringWithAggregatesFilter<"Drawing"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Drawing"> | Date | string
}

export type DrawingCreateInput = {
  id?: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutDrawingsInput
  extractedData?: Prisma.ExtractedDataCreateNestedManyWithoutDrawingInput
}

export type DrawingUncheckedCreateInput = {
  id?: string
  projectId: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
  extractedData?: Prisma.ExtractedDataUncheckedCreateNestedManyWithoutDrawingInput
}

export type DrawingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutDrawingsNestedInput
  extractedData?: Prisma.ExtractedDataUpdateManyWithoutDrawingNestedInput
}

export type DrawingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extractedData?: Prisma.ExtractedDataUncheckedUpdateManyWithoutDrawingNestedInput
}

export type DrawingCreateManyInput = {
  id?: string
  projectId: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
}

export type DrawingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DrawingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DrawingListRelationFilter = {
  every?: Prisma.DrawingWhereInput
  some?: Prisma.DrawingWhereInput
  none?: Prisma.DrawingWhereInput
}

export type DrawingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DrawingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DrawingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DrawingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DrawingScalarRelationFilter = {
  is?: Prisma.DrawingWhereInput
  isNot?: Prisma.DrawingWhereInput
}

export type DrawingCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.DrawingCreateWithoutProjectInput, Prisma.DrawingUncheckedCreateWithoutProjectInput> | Prisma.DrawingCreateWithoutProjectInput[] | Prisma.DrawingUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DrawingCreateOrConnectWithoutProjectInput | Prisma.DrawingCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.DrawingCreateManyProjectInputEnvelope
  connect?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
}

export type DrawingUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.DrawingCreateWithoutProjectInput, Prisma.DrawingUncheckedCreateWithoutProjectInput> | Prisma.DrawingCreateWithoutProjectInput[] | Prisma.DrawingUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DrawingCreateOrConnectWithoutProjectInput | Prisma.DrawingCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.DrawingCreateManyProjectInputEnvelope
  connect?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
}

export type DrawingUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.DrawingCreateWithoutProjectInput, Prisma.DrawingUncheckedCreateWithoutProjectInput> | Prisma.DrawingCreateWithoutProjectInput[] | Prisma.DrawingUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DrawingCreateOrConnectWithoutProjectInput | Prisma.DrawingCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.DrawingUpsertWithWhereUniqueWithoutProjectInput | Prisma.DrawingUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.DrawingCreateManyProjectInputEnvelope
  set?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  disconnect?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  delete?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  connect?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  update?: Prisma.DrawingUpdateWithWhereUniqueWithoutProjectInput | Prisma.DrawingUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.DrawingUpdateManyWithWhereWithoutProjectInput | Prisma.DrawingUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.DrawingScalarWhereInput | Prisma.DrawingScalarWhereInput[]
}

export type DrawingUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.DrawingCreateWithoutProjectInput, Prisma.DrawingUncheckedCreateWithoutProjectInput> | Prisma.DrawingCreateWithoutProjectInput[] | Prisma.DrawingUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DrawingCreateOrConnectWithoutProjectInput | Prisma.DrawingCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.DrawingUpsertWithWhereUniqueWithoutProjectInput | Prisma.DrawingUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.DrawingCreateManyProjectInputEnvelope
  set?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  disconnect?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  delete?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  connect?: Prisma.DrawingWhereUniqueInput | Prisma.DrawingWhereUniqueInput[]
  update?: Prisma.DrawingUpdateWithWhereUniqueWithoutProjectInput | Prisma.DrawingUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.DrawingUpdateManyWithWhereWithoutProjectInput | Prisma.DrawingUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.DrawingScalarWhereInput | Prisma.DrawingScalarWhereInput[]
}

export type DrawingCreateNestedOneWithoutExtractedDataInput = {
  create?: Prisma.XOR<Prisma.DrawingCreateWithoutExtractedDataInput, Prisma.DrawingUncheckedCreateWithoutExtractedDataInput>
  connectOrCreate?: Prisma.DrawingCreateOrConnectWithoutExtractedDataInput
  connect?: Prisma.DrawingWhereUniqueInput
}

export type DrawingUpdateOneRequiredWithoutExtractedDataNestedInput = {
  create?: Prisma.XOR<Prisma.DrawingCreateWithoutExtractedDataInput, Prisma.DrawingUncheckedCreateWithoutExtractedDataInput>
  connectOrCreate?: Prisma.DrawingCreateOrConnectWithoutExtractedDataInput
  upsert?: Prisma.DrawingUpsertWithoutExtractedDataInput
  connect?: Prisma.DrawingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DrawingUpdateToOneWithWhereWithoutExtractedDataInput, Prisma.DrawingUpdateWithoutExtractedDataInput>, Prisma.DrawingUncheckedUpdateWithoutExtractedDataInput>
}

export type DrawingCreateWithoutProjectInput = {
  id?: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
  extractedData?: Prisma.ExtractedDataCreateNestedManyWithoutDrawingInput
}

export type DrawingUncheckedCreateWithoutProjectInput = {
  id?: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
  extractedData?: Prisma.ExtractedDataUncheckedCreateNestedManyWithoutDrawingInput
}

export type DrawingCreateOrConnectWithoutProjectInput = {
  where: Prisma.DrawingWhereUniqueInput
  create: Prisma.XOR<Prisma.DrawingCreateWithoutProjectInput, Prisma.DrawingUncheckedCreateWithoutProjectInput>
}

export type DrawingCreateManyProjectInputEnvelope = {
  data: Prisma.DrawingCreateManyProjectInput | Prisma.DrawingCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type DrawingUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.DrawingWhereUniqueInput
  update: Prisma.XOR<Prisma.DrawingUpdateWithoutProjectInput, Prisma.DrawingUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.DrawingCreateWithoutProjectInput, Prisma.DrawingUncheckedCreateWithoutProjectInput>
}

export type DrawingUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.DrawingWhereUniqueInput
  data: Prisma.XOR<Prisma.DrawingUpdateWithoutProjectInput, Prisma.DrawingUncheckedUpdateWithoutProjectInput>
}

export type DrawingUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.DrawingScalarWhereInput
  data: Prisma.XOR<Prisma.DrawingUpdateManyMutationInput, Prisma.DrawingUncheckedUpdateManyWithoutProjectInput>
}

export type DrawingScalarWhereInput = {
  AND?: Prisma.DrawingScalarWhereInput | Prisma.DrawingScalarWhereInput[]
  OR?: Prisma.DrawingScalarWhereInput[]
  NOT?: Prisma.DrawingScalarWhereInput | Prisma.DrawingScalarWhereInput[]
  id?: Prisma.StringFilter<"Drawing"> | string
  projectId?: Prisma.StringFilter<"Drawing"> | string
  filename?: Prisma.StringFilter<"Drawing"> | string
  fileType?: Prisma.StringFilter<"Drawing"> | string
  filePath?: Prisma.StringFilter<"Drawing"> | string
  status?: Prisma.StringFilter<"Drawing"> | string
  createdAt?: Prisma.DateTimeFilter<"Drawing"> | Date | string
}

export type DrawingCreateWithoutExtractedDataInput = {
  id?: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutDrawingsInput
}

export type DrawingUncheckedCreateWithoutExtractedDataInput = {
  id?: string
  projectId: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
}

export type DrawingCreateOrConnectWithoutExtractedDataInput = {
  where: Prisma.DrawingWhereUniqueInput
  create: Prisma.XOR<Prisma.DrawingCreateWithoutExtractedDataInput, Prisma.DrawingUncheckedCreateWithoutExtractedDataInput>
}

export type DrawingUpsertWithoutExtractedDataInput = {
  update: Prisma.XOR<Prisma.DrawingUpdateWithoutExtractedDataInput, Prisma.DrawingUncheckedUpdateWithoutExtractedDataInput>
  create: Prisma.XOR<Prisma.DrawingCreateWithoutExtractedDataInput, Prisma.DrawingUncheckedCreateWithoutExtractedDataInput>
  where?: Prisma.DrawingWhereInput
}

export type DrawingUpdateToOneWithWhereWithoutExtractedDataInput = {
  where?: Prisma.DrawingWhereInput
  data: Prisma.XOR<Prisma.DrawingUpdateWithoutExtractedDataInput, Prisma.DrawingUncheckedUpdateWithoutExtractedDataInput>
}

export type DrawingUpdateWithoutExtractedDataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutDrawingsNestedInput
}

export type DrawingUncheckedUpdateWithoutExtractedDataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DrawingCreateManyProjectInput = {
  id?: string
  filename: string
  fileType: string
  filePath: string
  status?: string
  createdAt?: Date | string
}

export type DrawingUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extractedData?: Prisma.ExtractedDataUpdateManyWithoutDrawingNestedInput
}

export type DrawingUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extractedData?: Prisma.ExtractedDataUncheckedUpdateManyWithoutDrawingNestedInput
}

export type DrawingUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DrawingCountOutputType
 */

export type DrawingCountOutputType = {
  extractedData: number
}

export type DrawingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  extractedData?: boolean | DrawingCountOutputTypeCountExtractedDataArgs
}

/**
 * DrawingCountOutputType without action
 */
export type DrawingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DrawingCountOutputType
   */
  select?: Prisma.DrawingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DrawingCountOutputType without action
 */
export type DrawingCountOutputTypeCountExtractedDataArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExtractedDataWhereInput
}


export type DrawingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  filename?: boolean
  fileType?: boolean
  filePath?: boolean
  status?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  extractedData?: boolean | Prisma.Drawing$extractedDataArgs<ExtArgs>
  _count?: boolean | Prisma.DrawingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["drawing"]>

export type DrawingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  filename?: boolean
  fileType?: boolean
  filePath?: boolean
  status?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["drawing"]>

export type DrawingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  filename?: boolean
  fileType?: boolean
  filePath?: boolean
  status?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["drawing"]>

export type DrawingSelectScalar = {
  id?: boolean
  projectId?: boolean
  filename?: boolean
  fileType?: boolean
  filePath?: boolean
  status?: boolean
  createdAt?: boolean
}

export type DrawingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "filename" | "fileType" | "filePath" | "status" | "createdAt", ExtArgs["result"]["drawing"]>
export type DrawingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  extractedData?: boolean | Prisma.Drawing$extractedDataArgs<ExtArgs>
  _count?: boolean | Prisma.DrawingCountOutputTypeDefaultArgs<ExtArgs>
}
export type DrawingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type DrawingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $DrawingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Drawing"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    extractedData: Prisma.$ExtractedDataPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    filename: string
    fileType: string
    filePath: string
    status: string
    createdAt: Date
  }, ExtArgs["result"]["drawing"]>
  composites: {}
}

export type DrawingGetPayload<S extends boolean | null | undefined | DrawingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DrawingPayload, S>

export type DrawingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DrawingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DrawingCountAggregateInputType | true
  }

export interface DrawingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Drawing'], meta: { name: 'Drawing' } }
  /**
   * Find zero or one Drawing that matches the filter.
   * @param {DrawingFindUniqueArgs} args - Arguments to find a Drawing
   * @example
   * // Get one Drawing
   * const drawing = await prisma.drawing.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DrawingFindUniqueArgs>(args: Prisma.SelectSubset<T, DrawingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Drawing that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DrawingFindUniqueOrThrowArgs} args - Arguments to find a Drawing
   * @example
   * // Get one Drawing
   * const drawing = await prisma.drawing.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DrawingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DrawingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Drawing that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DrawingFindFirstArgs} args - Arguments to find a Drawing
   * @example
   * // Get one Drawing
   * const drawing = await prisma.drawing.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DrawingFindFirstArgs>(args?: Prisma.SelectSubset<T, DrawingFindFirstArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Drawing that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DrawingFindFirstOrThrowArgs} args - Arguments to find a Drawing
   * @example
   * // Get one Drawing
   * const drawing = await prisma.drawing.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DrawingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DrawingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Drawings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DrawingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Drawings
   * const drawings = await prisma.drawing.findMany()
   * 
   * // Get first 10 Drawings
   * const drawings = await prisma.drawing.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const drawingWithIdOnly = await prisma.drawing.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DrawingFindManyArgs>(args?: Prisma.SelectSubset<T, DrawingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Drawing.
   * @param {DrawingCreateArgs} args - Arguments to create a Drawing.
   * @example
   * // Create one Drawing
   * const Drawing = await prisma.drawing.create({
   *   data: {
   *     // ... data to create a Drawing
   *   }
   * })
   * 
   */
  create<T extends DrawingCreateArgs>(args: Prisma.SelectSubset<T, DrawingCreateArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Drawings.
   * @param {DrawingCreateManyArgs} args - Arguments to create many Drawings.
   * @example
   * // Create many Drawings
   * const drawing = await prisma.drawing.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DrawingCreateManyArgs>(args?: Prisma.SelectSubset<T, DrawingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Drawings and returns the data saved in the database.
   * @param {DrawingCreateManyAndReturnArgs} args - Arguments to create many Drawings.
   * @example
   * // Create many Drawings
   * const drawing = await prisma.drawing.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Drawings and only return the `id`
   * const drawingWithIdOnly = await prisma.drawing.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DrawingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DrawingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Drawing.
   * @param {DrawingDeleteArgs} args - Arguments to delete one Drawing.
   * @example
   * // Delete one Drawing
   * const Drawing = await prisma.drawing.delete({
   *   where: {
   *     // ... filter to delete one Drawing
   *   }
   * })
   * 
   */
  delete<T extends DrawingDeleteArgs>(args: Prisma.SelectSubset<T, DrawingDeleteArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Drawing.
   * @param {DrawingUpdateArgs} args - Arguments to update one Drawing.
   * @example
   * // Update one Drawing
   * const drawing = await prisma.drawing.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DrawingUpdateArgs>(args: Prisma.SelectSubset<T, DrawingUpdateArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Drawings.
   * @param {DrawingDeleteManyArgs} args - Arguments to filter Drawings to delete.
   * @example
   * // Delete a few Drawings
   * const { count } = await prisma.drawing.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DrawingDeleteManyArgs>(args?: Prisma.SelectSubset<T, DrawingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Drawings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DrawingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Drawings
   * const drawing = await prisma.drawing.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DrawingUpdateManyArgs>(args: Prisma.SelectSubset<T, DrawingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Drawings and returns the data updated in the database.
   * @param {DrawingUpdateManyAndReturnArgs} args - Arguments to update many Drawings.
   * @example
   * // Update many Drawings
   * const drawing = await prisma.drawing.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Drawings and only return the `id`
   * const drawingWithIdOnly = await prisma.drawing.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DrawingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DrawingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Drawing.
   * @param {DrawingUpsertArgs} args - Arguments to update or create a Drawing.
   * @example
   * // Update or create a Drawing
   * const drawing = await prisma.drawing.upsert({
   *   create: {
   *     // ... data to create a Drawing
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Drawing we want to update
   *   }
   * })
   */
  upsert<T extends DrawingUpsertArgs>(args: Prisma.SelectSubset<T, DrawingUpsertArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Drawings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DrawingCountArgs} args - Arguments to filter Drawings to count.
   * @example
   * // Count the number of Drawings
   * const count = await prisma.drawing.count({
   *   where: {
   *     // ... the filter for the Drawings we want to count
   *   }
   * })
  **/
  count<T extends DrawingCountArgs>(
    args?: Prisma.Subset<T, DrawingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DrawingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Drawing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DrawingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DrawingAggregateArgs>(args: Prisma.Subset<T, DrawingAggregateArgs>): Prisma.PrismaPromise<GetDrawingAggregateType<T>>

  /**
   * Group by Drawing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DrawingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DrawingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DrawingGroupByArgs['orderBy'] }
      : { orderBy?: DrawingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DrawingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDrawingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Drawing model
 */
readonly fields: DrawingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Drawing.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DrawingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  extractedData<T extends Prisma.Drawing$extractedDataArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Drawing$extractedDataArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Drawing model
 */
export interface DrawingFieldRefs {
  readonly id: Prisma.FieldRef<"Drawing", 'String'>
  readonly projectId: Prisma.FieldRef<"Drawing", 'String'>
  readonly filename: Prisma.FieldRef<"Drawing", 'String'>
  readonly fileType: Prisma.FieldRef<"Drawing", 'String'>
  readonly filePath: Prisma.FieldRef<"Drawing", 'String'>
  readonly status: Prisma.FieldRef<"Drawing", 'String'>
  readonly createdAt: Prisma.FieldRef<"Drawing", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Drawing findUnique
 */
export type DrawingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * Filter, which Drawing to fetch.
   */
  where: Prisma.DrawingWhereUniqueInput
}

/**
 * Drawing findUniqueOrThrow
 */
export type DrawingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * Filter, which Drawing to fetch.
   */
  where: Prisma.DrawingWhereUniqueInput
}

/**
 * Drawing findFirst
 */
export type DrawingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * Filter, which Drawing to fetch.
   */
  where?: Prisma.DrawingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drawings to fetch.
   */
  orderBy?: Prisma.DrawingOrderByWithRelationInput | Prisma.DrawingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Drawings.
   */
  cursor?: Prisma.DrawingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drawings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drawings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Drawings.
   */
  distinct?: Prisma.DrawingScalarFieldEnum | Prisma.DrawingScalarFieldEnum[]
}

/**
 * Drawing findFirstOrThrow
 */
export type DrawingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * Filter, which Drawing to fetch.
   */
  where?: Prisma.DrawingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drawings to fetch.
   */
  orderBy?: Prisma.DrawingOrderByWithRelationInput | Prisma.DrawingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Drawings.
   */
  cursor?: Prisma.DrawingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drawings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drawings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Drawings.
   */
  distinct?: Prisma.DrawingScalarFieldEnum | Prisma.DrawingScalarFieldEnum[]
}

/**
 * Drawing findMany
 */
export type DrawingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * Filter, which Drawings to fetch.
   */
  where?: Prisma.DrawingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drawings to fetch.
   */
  orderBy?: Prisma.DrawingOrderByWithRelationInput | Prisma.DrawingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Drawings.
   */
  cursor?: Prisma.DrawingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drawings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drawings.
   */
  skip?: number
  distinct?: Prisma.DrawingScalarFieldEnum | Prisma.DrawingScalarFieldEnum[]
}

/**
 * Drawing create
 */
export type DrawingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * The data needed to create a Drawing.
   */
  data: Prisma.XOR<Prisma.DrawingCreateInput, Prisma.DrawingUncheckedCreateInput>
}

/**
 * Drawing createMany
 */
export type DrawingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Drawings.
   */
  data: Prisma.DrawingCreateManyInput | Prisma.DrawingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Drawing createManyAndReturn
 */
export type DrawingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * The data used to create many Drawings.
   */
  data: Prisma.DrawingCreateManyInput | Prisma.DrawingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Drawing update
 */
export type DrawingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * The data needed to update a Drawing.
   */
  data: Prisma.XOR<Prisma.DrawingUpdateInput, Prisma.DrawingUncheckedUpdateInput>
  /**
   * Choose, which Drawing to update.
   */
  where: Prisma.DrawingWhereUniqueInput
}

/**
 * Drawing updateMany
 */
export type DrawingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Drawings.
   */
  data: Prisma.XOR<Prisma.DrawingUpdateManyMutationInput, Prisma.DrawingUncheckedUpdateManyInput>
  /**
   * Filter which Drawings to update
   */
  where?: Prisma.DrawingWhereInput
  /**
   * Limit how many Drawings to update.
   */
  limit?: number
}

/**
 * Drawing updateManyAndReturn
 */
export type DrawingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * The data used to update Drawings.
   */
  data: Prisma.XOR<Prisma.DrawingUpdateManyMutationInput, Prisma.DrawingUncheckedUpdateManyInput>
  /**
   * Filter which Drawings to update
   */
  where?: Prisma.DrawingWhereInput
  /**
   * Limit how many Drawings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Drawing upsert
 */
export type DrawingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * The filter to search for the Drawing to update in case it exists.
   */
  where: Prisma.DrawingWhereUniqueInput
  /**
   * In case the Drawing found by the `where` argument doesn't exist, create a new Drawing with this data.
   */
  create: Prisma.XOR<Prisma.DrawingCreateInput, Prisma.DrawingUncheckedCreateInput>
  /**
   * In case the Drawing was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DrawingUpdateInput, Prisma.DrawingUncheckedUpdateInput>
}

/**
 * Drawing delete
 */
export type DrawingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
  /**
   * Filter which Drawing to delete.
   */
  where: Prisma.DrawingWhereUniqueInput
}

/**
 * Drawing deleteMany
 */
export type DrawingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Drawings to delete
   */
  where?: Prisma.DrawingWhereInput
  /**
   * Limit how many Drawings to delete.
   */
  limit?: number
}

/**
 * Drawing.extractedData
 */
export type Drawing$extractedDataArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  where?: Prisma.ExtractedDataWhereInput
  orderBy?: Prisma.ExtractedDataOrderByWithRelationInput | Prisma.ExtractedDataOrderByWithRelationInput[]
  cursor?: Prisma.ExtractedDataWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExtractedDataScalarFieldEnum | Prisma.ExtractedDataScalarFieldEnum[]
}

/**
 * Drawing without action
 */
export type DrawingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drawing
   */
  select?: Prisma.DrawingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drawing
   */
  omit?: Prisma.DrawingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DrawingInclude<ExtArgs> | null
}
