
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ExtractedData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ExtractedData
 * 
 */
export type ExtractedDataModel = runtime.Types.Result.DefaultSelection<Prisma.$ExtractedDataPayload>

export type AggregateExtractedData = {
  _count: ExtractedDataCountAggregateOutputType | null
  _avg: ExtractedDataAvgAggregateOutputType | null
  _sum: ExtractedDataSumAggregateOutputType | null
  _min: ExtractedDataMinAggregateOutputType | null
  _max: ExtractedDataMaxAggregateOutputType | null
}

export type ExtractedDataAvgAggregateOutputType = {
  quantity: number | null
}

export type ExtractedDataSumAggregateOutputType = {
  quantity: number | null
}

export type ExtractedDataMinAggregateOutputType = {
  id: string | null
  drawingId: string | null
  materialType: string | null
  dimensions: string | null
  quantity: number | null
  annotations: string | null
  confidence: string | null
  rawData: string | null
  createdAt: Date | null
}

export type ExtractedDataMaxAggregateOutputType = {
  id: string | null
  drawingId: string | null
  materialType: string | null
  dimensions: string | null
  quantity: number | null
  annotations: string | null
  confidence: string | null
  rawData: string | null
  createdAt: Date | null
}

export type ExtractedDataCountAggregateOutputType = {
  id: number
  drawingId: number
  materialType: number
  dimensions: number
  quantity: number
  annotations: number
  confidence: number
  rawData: number
  createdAt: number
  _all: number
}


export type ExtractedDataAvgAggregateInputType = {
  quantity?: true
}

export type ExtractedDataSumAggregateInputType = {
  quantity?: true
}

export type ExtractedDataMinAggregateInputType = {
  id?: true
  drawingId?: true
  materialType?: true
  dimensions?: true
  quantity?: true
  annotations?: true
  confidence?: true
  rawData?: true
  createdAt?: true
}

export type ExtractedDataMaxAggregateInputType = {
  id?: true
  drawingId?: true
  materialType?: true
  dimensions?: true
  quantity?: true
  annotations?: true
  confidence?: true
  rawData?: true
  createdAt?: true
}

export type ExtractedDataCountAggregateInputType = {
  id?: true
  drawingId?: true
  materialType?: true
  dimensions?: true
  quantity?: true
  annotations?: true
  confidence?: true
  rawData?: true
  createdAt?: true
  _all?: true
}

export type ExtractedDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExtractedData to aggregate.
   */
  where?: Prisma.ExtractedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExtractedData to fetch.
   */
  orderBy?: Prisma.ExtractedDataOrderByWithRelationInput | Prisma.ExtractedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExtractedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExtractedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExtractedData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ExtractedData
  **/
  _count?: true | ExtractedDataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExtractedDataAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExtractedDataSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExtractedDataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExtractedDataMaxAggregateInputType
}

export type GetExtractedDataAggregateType<T extends ExtractedDataAggregateArgs> = {
      [P in keyof T & keyof AggregateExtractedData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExtractedData[P]>
    : Prisma.GetScalarType<T[P], AggregateExtractedData[P]>
}




export type ExtractedDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExtractedDataWhereInput
  orderBy?: Prisma.ExtractedDataOrderByWithAggregationInput | Prisma.ExtractedDataOrderByWithAggregationInput[]
  by: Prisma.ExtractedDataScalarFieldEnum[] | Prisma.ExtractedDataScalarFieldEnum
  having?: Prisma.ExtractedDataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExtractedDataCountAggregateInputType | true
  _avg?: ExtractedDataAvgAggregateInputType
  _sum?: ExtractedDataSumAggregateInputType
  _min?: ExtractedDataMinAggregateInputType
  _max?: ExtractedDataMaxAggregateInputType
}

export type ExtractedDataGroupByOutputType = {
  id: string
  drawingId: string
  materialType: string | null
  dimensions: string | null
  quantity: number | null
  annotations: string | null
  confidence: string | null
  rawData: string | null
  createdAt: Date
  _count: ExtractedDataCountAggregateOutputType | null
  _avg: ExtractedDataAvgAggregateOutputType | null
  _sum: ExtractedDataSumAggregateOutputType | null
  _min: ExtractedDataMinAggregateOutputType | null
  _max: ExtractedDataMaxAggregateOutputType | null
}

type GetExtractedDataGroupByPayload<T extends ExtractedDataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExtractedDataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExtractedDataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExtractedDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExtractedDataGroupByOutputType[P]>
      }
    >
  >



export type ExtractedDataWhereInput = {
  AND?: Prisma.ExtractedDataWhereInput | Prisma.ExtractedDataWhereInput[]
  OR?: Prisma.ExtractedDataWhereInput[]
  NOT?: Prisma.ExtractedDataWhereInput | Prisma.ExtractedDataWhereInput[]
  id?: Prisma.StringFilter<"ExtractedData"> | string
  drawingId?: Prisma.StringFilter<"ExtractedData"> | string
  materialType?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  dimensions?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  quantity?: Prisma.FloatNullableFilter<"ExtractedData"> | number | null
  annotations?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  confidence?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  rawData?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ExtractedData"> | Date | string
  drawing?: Prisma.XOR<Prisma.DrawingScalarRelationFilter, Prisma.DrawingWhereInput>
}

export type ExtractedDataOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  drawingId?: Prisma.SortOrder
  materialType?: Prisma.SortOrderInput | Prisma.SortOrder
  dimensions?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  annotations?: Prisma.SortOrderInput | Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  rawData?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  drawing?: Prisma.DrawingOrderByWithRelationInput
}

export type ExtractedDataWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ExtractedDataWhereInput | Prisma.ExtractedDataWhereInput[]
  OR?: Prisma.ExtractedDataWhereInput[]
  NOT?: Prisma.ExtractedDataWhereInput | Prisma.ExtractedDataWhereInput[]
  drawingId?: Prisma.StringFilter<"ExtractedData"> | string
  materialType?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  dimensions?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  quantity?: Prisma.FloatNullableFilter<"ExtractedData"> | number | null
  annotations?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  confidence?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  rawData?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ExtractedData"> | Date | string
  drawing?: Prisma.XOR<Prisma.DrawingScalarRelationFilter, Prisma.DrawingWhereInput>
}, "id">

export type ExtractedDataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  drawingId?: Prisma.SortOrder
  materialType?: Prisma.SortOrderInput | Prisma.SortOrder
  dimensions?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  annotations?: Prisma.SortOrderInput | Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  rawData?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ExtractedDataCountOrderByAggregateInput
  _avg?: Prisma.ExtractedDataAvgOrderByAggregateInput
  _max?: Prisma.ExtractedDataMaxOrderByAggregateInput
  _min?: Prisma.ExtractedDataMinOrderByAggregateInput
  _sum?: Prisma.ExtractedDataSumOrderByAggregateInput
}

export type ExtractedDataScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExtractedDataScalarWhereWithAggregatesInput | Prisma.ExtractedDataScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExtractedDataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExtractedDataScalarWhereWithAggregatesInput | Prisma.ExtractedDataScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ExtractedData"> | string
  drawingId?: Prisma.StringWithAggregatesFilter<"ExtractedData"> | string
  materialType?: Prisma.StringNullableWithAggregatesFilter<"ExtractedData"> | string | null
  dimensions?: Prisma.StringNullableWithAggregatesFilter<"ExtractedData"> | string | null
  quantity?: Prisma.FloatNullableWithAggregatesFilter<"ExtractedData"> | number | null
  annotations?: Prisma.StringNullableWithAggregatesFilter<"ExtractedData"> | string | null
  confidence?: Prisma.StringNullableWithAggregatesFilter<"ExtractedData"> | string | null
  rawData?: Prisma.StringNullableWithAggregatesFilter<"ExtractedData"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ExtractedData"> | Date | string
}

export type ExtractedDataCreateInput = {
  id?: string
  materialType?: string | null
  dimensions?: string | null
  quantity?: number | null
  annotations?: string | null
  confidence?: string | null
  rawData?: string | null
  createdAt?: Date | string
  drawing: Prisma.DrawingCreateNestedOneWithoutExtractedDataInput
}

export type ExtractedDataUncheckedCreateInput = {
  id?: string
  drawingId: string
  materialType?: string | null
  dimensions?: string | null
  quantity?: number | null
  annotations?: string | null
  confidence?: string | null
  rawData?: string | null
  createdAt?: Date | string
}

export type ExtractedDataUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  annotations?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  drawing?: Prisma.DrawingUpdateOneRequiredWithoutExtractedDataNestedInput
}

export type ExtractedDataUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  drawingId?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  annotations?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractedDataCreateManyInput = {
  id?: string
  drawingId: string
  materialType?: string | null
  dimensions?: string | null
  quantity?: number | null
  annotations?: string | null
  confidence?: string | null
  rawData?: string | null
  createdAt?: Date | string
}

export type ExtractedDataUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  annotations?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractedDataUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  drawingId?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  annotations?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractedDataListRelationFilter = {
  every?: Prisma.ExtractedDataWhereInput
  some?: Prisma.ExtractedDataWhereInput
  none?: Prisma.ExtractedDataWhereInput
}

export type ExtractedDataOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExtractedDataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  drawingId?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  dimensions?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  annotations?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  rawData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExtractedDataAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type ExtractedDataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  drawingId?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  dimensions?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  annotations?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  rawData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExtractedDataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  drawingId?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  dimensions?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  annotations?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  rawData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExtractedDataSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type ExtractedDataCreateNestedManyWithoutDrawingInput = {
  create?: Prisma.XOR<Prisma.ExtractedDataCreateWithoutDrawingInput, Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput> | Prisma.ExtractedDataCreateWithoutDrawingInput[] | Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput[]
  connectOrCreate?: Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput | Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput[]
  createMany?: Prisma.ExtractedDataCreateManyDrawingInputEnvelope
  connect?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
}

export type ExtractedDataUncheckedCreateNestedManyWithoutDrawingInput = {
  create?: Prisma.XOR<Prisma.ExtractedDataCreateWithoutDrawingInput, Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput> | Prisma.ExtractedDataCreateWithoutDrawingInput[] | Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput[]
  connectOrCreate?: Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput | Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput[]
  createMany?: Prisma.ExtractedDataCreateManyDrawingInputEnvelope
  connect?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
}

export type ExtractedDataUpdateManyWithoutDrawingNestedInput = {
  create?: Prisma.XOR<Prisma.ExtractedDataCreateWithoutDrawingInput, Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput> | Prisma.ExtractedDataCreateWithoutDrawingInput[] | Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput[]
  connectOrCreate?: Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput | Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput[]
  upsert?: Prisma.ExtractedDataUpsertWithWhereUniqueWithoutDrawingInput | Prisma.ExtractedDataUpsertWithWhereUniqueWithoutDrawingInput[]
  createMany?: Prisma.ExtractedDataCreateManyDrawingInputEnvelope
  set?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  disconnect?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  delete?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  connect?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  update?: Prisma.ExtractedDataUpdateWithWhereUniqueWithoutDrawingInput | Prisma.ExtractedDataUpdateWithWhereUniqueWithoutDrawingInput[]
  updateMany?: Prisma.ExtractedDataUpdateManyWithWhereWithoutDrawingInput | Prisma.ExtractedDataUpdateManyWithWhereWithoutDrawingInput[]
  deleteMany?: Prisma.ExtractedDataScalarWhereInput | Prisma.ExtractedDataScalarWhereInput[]
}

export type ExtractedDataUncheckedUpdateManyWithoutDrawingNestedInput = {
  create?: Prisma.XOR<Prisma.ExtractedDataCreateWithoutDrawingInput, Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput> | Prisma.ExtractedDataCreateWithoutDrawingInput[] | Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput[]
  connectOrCreate?: Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput | Prisma.ExtractedDataCreateOrConnectWithoutDrawingInput[]
  upsert?: Prisma.ExtractedDataUpsertWithWhereUniqueWithoutDrawingInput | Prisma.ExtractedDataUpsertWithWhereUniqueWithoutDrawingInput[]
  createMany?: Prisma.ExtractedDataCreateManyDrawingInputEnvelope
  set?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  disconnect?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  delete?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  connect?: Prisma.ExtractedDataWhereUniqueInput | Prisma.ExtractedDataWhereUniqueInput[]
  update?: Prisma.ExtractedDataUpdateWithWhereUniqueWithoutDrawingInput | Prisma.ExtractedDataUpdateWithWhereUniqueWithoutDrawingInput[]
  updateMany?: Prisma.ExtractedDataUpdateManyWithWhereWithoutDrawingInput | Prisma.ExtractedDataUpdateManyWithWhereWithoutDrawingInput[]
  deleteMany?: Prisma.ExtractedDataScalarWhereInput | Prisma.ExtractedDataScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ExtractedDataCreateWithoutDrawingInput = {
  id?: string
  materialType?: string | null
  dimensions?: string | null
  quantity?: number | null
  annotations?: string | null
  confidence?: string | null
  rawData?: string | null
  createdAt?: Date | string
}

export type ExtractedDataUncheckedCreateWithoutDrawingInput = {
  id?: string
  materialType?: string | null
  dimensions?: string | null
  quantity?: number | null
  annotations?: string | null
  confidence?: string | null
  rawData?: string | null
  createdAt?: Date | string
}

export type ExtractedDataCreateOrConnectWithoutDrawingInput = {
  where: Prisma.ExtractedDataWhereUniqueInput
  create: Prisma.XOR<Prisma.ExtractedDataCreateWithoutDrawingInput, Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput>
}

export type ExtractedDataCreateManyDrawingInputEnvelope = {
  data: Prisma.ExtractedDataCreateManyDrawingInput | Prisma.ExtractedDataCreateManyDrawingInput[]
}

export type ExtractedDataUpsertWithWhereUniqueWithoutDrawingInput = {
  where: Prisma.ExtractedDataWhereUniqueInput
  update: Prisma.XOR<Prisma.ExtractedDataUpdateWithoutDrawingInput, Prisma.ExtractedDataUncheckedUpdateWithoutDrawingInput>
  create: Prisma.XOR<Prisma.ExtractedDataCreateWithoutDrawingInput, Prisma.ExtractedDataUncheckedCreateWithoutDrawingInput>
}

export type ExtractedDataUpdateWithWhereUniqueWithoutDrawingInput = {
  where: Prisma.ExtractedDataWhereUniqueInput
  data: Prisma.XOR<Prisma.ExtractedDataUpdateWithoutDrawingInput, Prisma.ExtractedDataUncheckedUpdateWithoutDrawingInput>
}

export type ExtractedDataUpdateManyWithWhereWithoutDrawingInput = {
  where: Prisma.ExtractedDataScalarWhereInput
  data: Prisma.XOR<Prisma.ExtractedDataUpdateManyMutationInput, Prisma.ExtractedDataUncheckedUpdateManyWithoutDrawingInput>
}

export type ExtractedDataScalarWhereInput = {
  AND?: Prisma.ExtractedDataScalarWhereInput | Prisma.ExtractedDataScalarWhereInput[]
  OR?: Prisma.ExtractedDataScalarWhereInput[]
  NOT?: Prisma.ExtractedDataScalarWhereInput | Prisma.ExtractedDataScalarWhereInput[]
  id?: Prisma.StringFilter<"ExtractedData"> | string
  drawingId?: Prisma.StringFilter<"ExtractedData"> | string
  materialType?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  dimensions?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  quantity?: Prisma.FloatNullableFilter<"ExtractedData"> | number | null
  annotations?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  confidence?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  rawData?: Prisma.StringNullableFilter<"ExtractedData"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ExtractedData"> | Date | string
}

export type ExtractedDataCreateManyDrawingInput = {
  id?: string
  materialType?: string | null
  dimensions?: string | null
  quantity?: number | null
  annotations?: string | null
  confidence?: string | null
  rawData?: string | null
  createdAt?: Date | string
}

export type ExtractedDataUpdateWithoutDrawingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  annotations?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractedDataUncheckedUpdateWithoutDrawingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  annotations?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractedDataUncheckedUpdateManyWithoutDrawingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  annotations?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ExtractedDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  drawingId?: boolean
  materialType?: boolean
  dimensions?: boolean
  quantity?: boolean
  annotations?: boolean
  confidence?: boolean
  rawData?: boolean
  createdAt?: boolean
  drawing?: boolean | Prisma.DrawingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["extractedData"]>

export type ExtractedDataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  drawingId?: boolean
  materialType?: boolean
  dimensions?: boolean
  quantity?: boolean
  annotations?: boolean
  confidence?: boolean
  rawData?: boolean
  createdAt?: boolean
  drawing?: boolean | Prisma.DrawingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["extractedData"]>

export type ExtractedDataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  drawingId?: boolean
  materialType?: boolean
  dimensions?: boolean
  quantity?: boolean
  annotations?: boolean
  confidence?: boolean
  rawData?: boolean
  createdAt?: boolean
  drawing?: boolean | Prisma.DrawingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["extractedData"]>

export type ExtractedDataSelectScalar = {
  id?: boolean
  drawingId?: boolean
  materialType?: boolean
  dimensions?: boolean
  quantity?: boolean
  annotations?: boolean
  confidence?: boolean
  rawData?: boolean
  createdAt?: boolean
}

export type ExtractedDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "drawingId" | "materialType" | "dimensions" | "quantity" | "annotations" | "confidence" | "rawData" | "createdAt", ExtArgs["result"]["extractedData"]>
export type ExtractedDataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  drawing?: boolean | Prisma.DrawingDefaultArgs<ExtArgs>
}
export type ExtractedDataIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  drawing?: boolean | Prisma.DrawingDefaultArgs<ExtArgs>
}
export type ExtractedDataIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  drawing?: boolean | Prisma.DrawingDefaultArgs<ExtArgs>
}

export type $ExtractedDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ExtractedData"
  objects: {
    drawing: Prisma.$DrawingPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    drawingId: string
    materialType: string | null
    dimensions: string | null
    quantity: number | null
    annotations: string | null
    confidence: string | null
    rawData: string | null
    createdAt: Date
  }, ExtArgs["result"]["extractedData"]>
  composites: {}
}

export type ExtractedDataGetPayload<S extends boolean | null | undefined | ExtractedDataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload, S>

export type ExtractedDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExtractedDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExtractedDataCountAggregateInputType | true
  }

export interface ExtractedDataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ExtractedData'], meta: { name: 'ExtractedData' } }
  /**
   * Find zero or one ExtractedData that matches the filter.
   * @param {ExtractedDataFindUniqueArgs} args - Arguments to find a ExtractedData
   * @example
   * // Get one ExtractedData
   * const extractedData = await prisma.extractedData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExtractedDataFindUniqueArgs>(args: Prisma.SelectSubset<T, ExtractedDataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ExtractedData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExtractedDataFindUniqueOrThrowArgs} args - Arguments to find a ExtractedData
   * @example
   * // Get one ExtractedData
   * const extractedData = await prisma.extractedData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExtractedDataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExtractedDataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExtractedData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractedDataFindFirstArgs} args - Arguments to find a ExtractedData
   * @example
   * // Get one ExtractedData
   * const extractedData = await prisma.extractedData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExtractedDataFindFirstArgs>(args?: Prisma.SelectSubset<T, ExtractedDataFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExtractedData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractedDataFindFirstOrThrowArgs} args - Arguments to find a ExtractedData
   * @example
   * // Get one ExtractedData
   * const extractedData = await prisma.extractedData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExtractedDataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExtractedDataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ExtractedData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractedDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExtractedData
   * const extractedData = await prisma.extractedData.findMany()
   * 
   * // Get first 10 ExtractedData
   * const extractedData = await prisma.extractedData.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const extractedDataWithIdOnly = await prisma.extractedData.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExtractedDataFindManyArgs>(args?: Prisma.SelectSubset<T, ExtractedDataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ExtractedData.
   * @param {ExtractedDataCreateArgs} args - Arguments to create a ExtractedData.
   * @example
   * // Create one ExtractedData
   * const ExtractedData = await prisma.extractedData.create({
   *   data: {
   *     // ... data to create a ExtractedData
   *   }
   * })
   * 
   */
  create<T extends ExtractedDataCreateArgs>(args: Prisma.SelectSubset<T, ExtractedDataCreateArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ExtractedData.
   * @param {ExtractedDataCreateManyArgs} args - Arguments to create many ExtractedData.
   * @example
   * // Create many ExtractedData
   * const extractedData = await prisma.extractedData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExtractedDataCreateManyArgs>(args?: Prisma.SelectSubset<T, ExtractedDataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ExtractedData and returns the data saved in the database.
   * @param {ExtractedDataCreateManyAndReturnArgs} args - Arguments to create many ExtractedData.
   * @example
   * // Create many ExtractedData
   * const extractedData = await prisma.extractedData.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ExtractedData and only return the `id`
   * const extractedDataWithIdOnly = await prisma.extractedData.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExtractedDataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExtractedDataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ExtractedData.
   * @param {ExtractedDataDeleteArgs} args - Arguments to delete one ExtractedData.
   * @example
   * // Delete one ExtractedData
   * const ExtractedData = await prisma.extractedData.delete({
   *   where: {
   *     // ... filter to delete one ExtractedData
   *   }
   * })
   * 
   */
  delete<T extends ExtractedDataDeleteArgs>(args: Prisma.SelectSubset<T, ExtractedDataDeleteArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ExtractedData.
   * @param {ExtractedDataUpdateArgs} args - Arguments to update one ExtractedData.
   * @example
   * // Update one ExtractedData
   * const extractedData = await prisma.extractedData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExtractedDataUpdateArgs>(args: Prisma.SelectSubset<T, ExtractedDataUpdateArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ExtractedData.
   * @param {ExtractedDataDeleteManyArgs} args - Arguments to filter ExtractedData to delete.
   * @example
   * // Delete a few ExtractedData
   * const { count } = await prisma.extractedData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExtractedDataDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExtractedDataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExtractedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractedDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExtractedData
   * const extractedData = await prisma.extractedData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExtractedDataUpdateManyArgs>(args: Prisma.SelectSubset<T, ExtractedDataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExtractedData and returns the data updated in the database.
   * @param {ExtractedDataUpdateManyAndReturnArgs} args - Arguments to update many ExtractedData.
   * @example
   * // Update many ExtractedData
   * const extractedData = await prisma.extractedData.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ExtractedData and only return the `id`
   * const extractedDataWithIdOnly = await prisma.extractedData.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExtractedDataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExtractedDataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ExtractedData.
   * @param {ExtractedDataUpsertArgs} args - Arguments to update or create a ExtractedData.
   * @example
   * // Update or create a ExtractedData
   * const extractedData = await prisma.extractedData.upsert({
   *   create: {
   *     // ... data to create a ExtractedData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExtractedData we want to update
   *   }
   * })
   */
  upsert<T extends ExtractedDataUpsertArgs>(args: Prisma.SelectSubset<T, ExtractedDataUpsertArgs<ExtArgs>>): Prisma.Prisma__ExtractedDataClient<runtime.Types.Result.GetResult<Prisma.$ExtractedDataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ExtractedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractedDataCountArgs} args - Arguments to filter ExtractedData to count.
   * @example
   * // Count the number of ExtractedData
   * const count = await prisma.extractedData.count({
   *   where: {
   *     // ... the filter for the ExtractedData we want to count
   *   }
   * })
  **/
  count<T extends ExtractedDataCountArgs>(
    args?: Prisma.Subset<T, ExtractedDataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExtractedDataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ExtractedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractedDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExtractedDataAggregateArgs>(args: Prisma.Subset<T, ExtractedDataAggregateArgs>): Prisma.PrismaPromise<GetExtractedDataAggregateType<T>>

  /**
   * Group by ExtractedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractedDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExtractedDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExtractedDataGroupByArgs['orderBy'] }
      : { orderBy?: ExtractedDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExtractedDataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExtractedDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ExtractedData model
 */
readonly fields: ExtractedDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ExtractedData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExtractedDataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  drawing<T extends Prisma.DrawingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DrawingDefaultArgs<ExtArgs>>): Prisma.Prisma__DrawingClient<runtime.Types.Result.GetResult<Prisma.$DrawingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ExtractedData model
 */
export interface ExtractedDataFieldRefs {
  readonly id: Prisma.FieldRef<"ExtractedData", 'String'>
  readonly drawingId: Prisma.FieldRef<"ExtractedData", 'String'>
  readonly materialType: Prisma.FieldRef<"ExtractedData", 'String'>
  readonly dimensions: Prisma.FieldRef<"ExtractedData", 'String'>
  readonly quantity: Prisma.FieldRef<"ExtractedData", 'Float'>
  readonly annotations: Prisma.FieldRef<"ExtractedData", 'String'>
  readonly confidence: Prisma.FieldRef<"ExtractedData", 'String'>
  readonly rawData: Prisma.FieldRef<"ExtractedData", 'String'>
  readonly createdAt: Prisma.FieldRef<"ExtractedData", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ExtractedData findUnique
 */
export type ExtractedDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * Filter, which ExtractedData to fetch.
   */
  where: Prisma.ExtractedDataWhereUniqueInput
}

/**
 * ExtractedData findUniqueOrThrow
 */
export type ExtractedDataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * Filter, which ExtractedData to fetch.
   */
  where: Prisma.ExtractedDataWhereUniqueInput
}

/**
 * ExtractedData findFirst
 */
export type ExtractedDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * Filter, which ExtractedData to fetch.
   */
  where?: Prisma.ExtractedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExtractedData to fetch.
   */
  orderBy?: Prisma.ExtractedDataOrderByWithRelationInput | Prisma.ExtractedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExtractedData.
   */
  cursor?: Prisma.ExtractedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExtractedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExtractedData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExtractedData.
   */
  distinct?: Prisma.ExtractedDataScalarFieldEnum | Prisma.ExtractedDataScalarFieldEnum[]
}

/**
 * ExtractedData findFirstOrThrow
 */
export type ExtractedDataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * Filter, which ExtractedData to fetch.
   */
  where?: Prisma.ExtractedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExtractedData to fetch.
   */
  orderBy?: Prisma.ExtractedDataOrderByWithRelationInput | Prisma.ExtractedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExtractedData.
   */
  cursor?: Prisma.ExtractedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExtractedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExtractedData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExtractedData.
   */
  distinct?: Prisma.ExtractedDataScalarFieldEnum | Prisma.ExtractedDataScalarFieldEnum[]
}

/**
 * ExtractedData findMany
 */
export type ExtractedDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * Filter, which ExtractedData to fetch.
   */
  where?: Prisma.ExtractedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExtractedData to fetch.
   */
  orderBy?: Prisma.ExtractedDataOrderByWithRelationInput | Prisma.ExtractedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ExtractedData.
   */
  cursor?: Prisma.ExtractedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExtractedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExtractedData.
   */
  skip?: number
  distinct?: Prisma.ExtractedDataScalarFieldEnum | Prisma.ExtractedDataScalarFieldEnum[]
}

/**
 * ExtractedData create
 */
export type ExtractedDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * The data needed to create a ExtractedData.
   */
  data: Prisma.XOR<Prisma.ExtractedDataCreateInput, Prisma.ExtractedDataUncheckedCreateInput>
}

/**
 * ExtractedData createMany
 */
export type ExtractedDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ExtractedData.
   */
  data: Prisma.ExtractedDataCreateManyInput | Prisma.ExtractedDataCreateManyInput[]
}

/**
 * ExtractedData createManyAndReturn
 */
export type ExtractedDataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * The data used to create many ExtractedData.
   */
  data: Prisma.ExtractedDataCreateManyInput | Prisma.ExtractedDataCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ExtractedData update
 */
export type ExtractedDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * The data needed to update a ExtractedData.
   */
  data: Prisma.XOR<Prisma.ExtractedDataUpdateInput, Prisma.ExtractedDataUncheckedUpdateInput>
  /**
   * Choose, which ExtractedData to update.
   */
  where: Prisma.ExtractedDataWhereUniqueInput
}

/**
 * ExtractedData updateMany
 */
export type ExtractedDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ExtractedData.
   */
  data: Prisma.XOR<Prisma.ExtractedDataUpdateManyMutationInput, Prisma.ExtractedDataUncheckedUpdateManyInput>
  /**
   * Filter which ExtractedData to update
   */
  where?: Prisma.ExtractedDataWhereInput
  /**
   * Limit how many ExtractedData to update.
   */
  limit?: number
}

/**
 * ExtractedData updateManyAndReturn
 */
export type ExtractedDataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * The data used to update ExtractedData.
   */
  data: Prisma.XOR<Prisma.ExtractedDataUpdateManyMutationInput, Prisma.ExtractedDataUncheckedUpdateManyInput>
  /**
   * Filter which ExtractedData to update
   */
  where?: Prisma.ExtractedDataWhereInput
  /**
   * Limit how many ExtractedData to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ExtractedData upsert
 */
export type ExtractedDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * The filter to search for the ExtractedData to update in case it exists.
   */
  where: Prisma.ExtractedDataWhereUniqueInput
  /**
   * In case the ExtractedData found by the `where` argument doesn't exist, create a new ExtractedData with this data.
   */
  create: Prisma.XOR<Prisma.ExtractedDataCreateInput, Prisma.ExtractedDataUncheckedCreateInput>
  /**
   * In case the ExtractedData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExtractedDataUpdateInput, Prisma.ExtractedDataUncheckedUpdateInput>
}

/**
 * ExtractedData delete
 */
export type ExtractedDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
  /**
   * Filter which ExtractedData to delete.
   */
  where: Prisma.ExtractedDataWhereUniqueInput
}

/**
 * ExtractedData deleteMany
 */
export type ExtractedDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExtractedData to delete
   */
  where?: Prisma.ExtractedDataWhereInput
  /**
   * Limit how many ExtractedData to delete.
   */
  limit?: number
}

/**
 * ExtractedData without action
 */
export type ExtractedDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExtractedData
   */
  select?: Prisma.ExtractedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExtractedData
   */
  omit?: Prisma.ExtractedDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractedDataInclude<ExtArgs> | null
}
