
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MaterialRate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MaterialRate
 * 
 */
export type MaterialRateModel = runtime.Types.Result.DefaultSelection<Prisma.$MaterialRatePayload>

export type AggregateMaterialRate = {
  _count: MaterialRateCountAggregateOutputType | null
  _avg: MaterialRateAvgAggregateOutputType | null
  _sum: MaterialRateSumAggregateOutputType | null
  _min: MaterialRateMinAggregateOutputType | null
  _max: MaterialRateMaxAggregateOutputType | null
}

export type MaterialRateAvgAggregateOutputType = {
  rate: number | null
}

export type MaterialRateSumAggregateOutputType = {
  rate: number | null
}

export type MaterialRateMinAggregateOutputType = {
  id: string | null
  materialType: string | null
  unit: string | null
  rate: number | null
  currency: string | null
  source: string | null
  updatedAt: Date | null
}

export type MaterialRateMaxAggregateOutputType = {
  id: string | null
  materialType: string | null
  unit: string | null
  rate: number | null
  currency: string | null
  source: string | null
  updatedAt: Date | null
}

export type MaterialRateCountAggregateOutputType = {
  id: number
  materialType: number
  unit: number
  rate: number
  currency: number
  source: number
  updatedAt: number
  _all: number
}


export type MaterialRateAvgAggregateInputType = {
  rate?: true
}

export type MaterialRateSumAggregateInputType = {
  rate?: true
}

export type MaterialRateMinAggregateInputType = {
  id?: true
  materialType?: true
  unit?: true
  rate?: true
  currency?: true
  source?: true
  updatedAt?: true
}

export type MaterialRateMaxAggregateInputType = {
  id?: true
  materialType?: true
  unit?: true
  rate?: true
  currency?: true
  source?: true
  updatedAt?: true
}

export type MaterialRateCountAggregateInputType = {
  id?: true
  materialType?: true
  unit?: true
  rate?: true
  currency?: true
  source?: true
  updatedAt?: true
  _all?: true
}

export type MaterialRateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaterialRate to aggregate.
   */
  where?: Prisma.MaterialRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialRates to fetch.
   */
  orderBy?: Prisma.MaterialRateOrderByWithRelationInput | Prisma.MaterialRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaterialRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MaterialRates
  **/
  _count?: true | MaterialRateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MaterialRateAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MaterialRateSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaterialRateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaterialRateMaxAggregateInputType
}

export type GetMaterialRateAggregateType<T extends MaterialRateAggregateArgs> = {
      [P in keyof T & keyof AggregateMaterialRate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaterialRate[P]>
    : Prisma.GetScalarType<T[P], AggregateMaterialRate[P]>
}




export type MaterialRateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaterialRateWhereInput
  orderBy?: Prisma.MaterialRateOrderByWithAggregationInput | Prisma.MaterialRateOrderByWithAggregationInput[]
  by: Prisma.MaterialRateScalarFieldEnum[] | Prisma.MaterialRateScalarFieldEnum
  having?: Prisma.MaterialRateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaterialRateCountAggregateInputType | true
  _avg?: MaterialRateAvgAggregateInputType
  _sum?: MaterialRateSumAggregateInputType
  _min?: MaterialRateMinAggregateInputType
  _max?: MaterialRateMaxAggregateInputType
}

export type MaterialRateGroupByOutputType = {
  id: string
  materialType: string
  unit: string | null
  rate: number | null
  currency: string | null
  source: string | null
  updatedAt: Date
  _count: MaterialRateCountAggregateOutputType | null
  _avg: MaterialRateAvgAggregateOutputType | null
  _sum: MaterialRateSumAggregateOutputType | null
  _min: MaterialRateMinAggregateOutputType | null
  _max: MaterialRateMaxAggregateOutputType | null
}

type GetMaterialRateGroupByPayload<T extends MaterialRateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaterialRateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaterialRateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaterialRateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaterialRateGroupByOutputType[P]>
      }
    >
  >



export type MaterialRateWhereInput = {
  AND?: Prisma.MaterialRateWhereInput | Prisma.MaterialRateWhereInput[]
  OR?: Prisma.MaterialRateWhereInput[]
  NOT?: Prisma.MaterialRateWhereInput | Prisma.MaterialRateWhereInput[]
  id?: Prisma.StringFilter<"MaterialRate"> | string
  materialType?: Prisma.StringFilter<"MaterialRate"> | string
  unit?: Prisma.StringNullableFilter<"MaterialRate"> | string | null
  rate?: Prisma.FloatNullableFilter<"MaterialRate"> | number | null
  currency?: Prisma.StringNullableFilter<"MaterialRate"> | string | null
  source?: Prisma.StringNullableFilter<"MaterialRate"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"MaterialRate"> | Date | string
}

export type MaterialRateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  unit?: Prisma.SortOrderInput | Prisma.SortOrder
  rate?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaterialRateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MaterialRateWhereInput | Prisma.MaterialRateWhereInput[]
  OR?: Prisma.MaterialRateWhereInput[]
  NOT?: Prisma.MaterialRateWhereInput | Prisma.MaterialRateWhereInput[]
  materialType?: Prisma.StringFilter<"MaterialRate"> | string
  unit?: Prisma.StringNullableFilter<"MaterialRate"> | string | null
  rate?: Prisma.FloatNullableFilter<"MaterialRate"> | number | null
  currency?: Prisma.StringNullableFilter<"MaterialRate"> | string | null
  source?: Prisma.StringNullableFilter<"MaterialRate"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"MaterialRate"> | Date | string
}, "id">

export type MaterialRateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  unit?: Prisma.SortOrderInput | Prisma.SortOrder
  rate?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MaterialRateCountOrderByAggregateInput
  _avg?: Prisma.MaterialRateAvgOrderByAggregateInput
  _max?: Prisma.MaterialRateMaxOrderByAggregateInput
  _min?: Prisma.MaterialRateMinOrderByAggregateInput
  _sum?: Prisma.MaterialRateSumOrderByAggregateInput
}

export type MaterialRateScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaterialRateScalarWhereWithAggregatesInput | Prisma.MaterialRateScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaterialRateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaterialRateScalarWhereWithAggregatesInput | Prisma.MaterialRateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MaterialRate"> | string
  materialType?: Prisma.StringWithAggregatesFilter<"MaterialRate"> | string
  unit?: Prisma.StringNullableWithAggregatesFilter<"MaterialRate"> | string | null
  rate?: Prisma.FloatNullableWithAggregatesFilter<"MaterialRate"> | number | null
  currency?: Prisma.StringNullableWithAggregatesFilter<"MaterialRate"> | string | null
  source?: Prisma.StringNullableWithAggregatesFilter<"MaterialRate"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MaterialRate"> | Date | string
}

export type MaterialRateCreateInput = {
  id?: string
  materialType: string
  unit?: string | null
  rate?: number | null
  currency?: string | null
  source?: string | null
  updatedAt?: Date | string
}

export type MaterialRateUncheckedCreateInput = {
  id?: string
  materialType: string
  unit?: string | null
  rate?: number | null
  currency?: string | null
  source?: string | null
  updatedAt?: Date | string
}

export type MaterialRateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialRateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialRateCreateManyInput = {
  id?: string
  materialType: string
  unit?: string | null
  rate?: number | null
  currency?: string | null
  source?: string | null
  updatedAt?: Date | string
}

export type MaterialRateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialRateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialType?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialRateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  source?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaterialRateAvgOrderByAggregateInput = {
  rate?: Prisma.SortOrder
}

export type MaterialRateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  source?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaterialRateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  materialType?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  source?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaterialRateSumOrderByAggregateInput = {
  rate?: Prisma.SortOrder
}



export type MaterialRateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  materialType?: boolean
  unit?: boolean
  rate?: boolean
  currency?: boolean
  source?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["materialRate"]>

export type MaterialRateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  materialType?: boolean
  unit?: boolean
  rate?: boolean
  currency?: boolean
  source?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["materialRate"]>

export type MaterialRateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  materialType?: boolean
  unit?: boolean
  rate?: boolean
  currency?: boolean
  source?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["materialRate"]>

export type MaterialRateSelectScalar = {
  id?: boolean
  materialType?: boolean
  unit?: boolean
  rate?: boolean
  currency?: boolean
  source?: boolean
  updatedAt?: boolean
}

export type MaterialRateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "materialType" | "unit" | "rate" | "currency" | "source" | "updatedAt", ExtArgs["result"]["materialRate"]>

export type $MaterialRatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MaterialRate"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    materialType: string
    unit: string | null
    rate: number | null
    currency: string | null
    source: string | null
    updatedAt: Date
  }, ExtArgs["result"]["materialRate"]>
  composites: {}
}

export type MaterialRateGetPayload<S extends boolean | null | undefined | MaterialRateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload, S>

export type MaterialRateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaterialRateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaterialRateCountAggregateInputType | true
  }

export interface MaterialRateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MaterialRate'], meta: { name: 'MaterialRate' } }
  /**
   * Find zero or one MaterialRate that matches the filter.
   * @param {MaterialRateFindUniqueArgs} args - Arguments to find a MaterialRate
   * @example
   * // Get one MaterialRate
   * const materialRate = await prisma.materialRate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaterialRateFindUniqueArgs>(args: Prisma.SelectSubset<T, MaterialRateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MaterialRate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaterialRateFindUniqueOrThrowArgs} args - Arguments to find a MaterialRate
   * @example
   * // Get one MaterialRate
   * const materialRate = await prisma.materialRate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaterialRateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaterialRateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaterialRate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialRateFindFirstArgs} args - Arguments to find a MaterialRate
   * @example
   * // Get one MaterialRate
   * const materialRate = await prisma.materialRate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaterialRateFindFirstArgs>(args?: Prisma.SelectSubset<T, MaterialRateFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaterialRate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialRateFindFirstOrThrowArgs} args - Arguments to find a MaterialRate
   * @example
   * // Get one MaterialRate
   * const materialRate = await prisma.materialRate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaterialRateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaterialRateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MaterialRates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialRateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MaterialRates
   * const materialRates = await prisma.materialRate.findMany()
   * 
   * // Get first 10 MaterialRates
   * const materialRates = await prisma.materialRate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const materialRateWithIdOnly = await prisma.materialRate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MaterialRateFindManyArgs>(args?: Prisma.SelectSubset<T, MaterialRateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MaterialRate.
   * @param {MaterialRateCreateArgs} args - Arguments to create a MaterialRate.
   * @example
   * // Create one MaterialRate
   * const MaterialRate = await prisma.materialRate.create({
   *   data: {
   *     // ... data to create a MaterialRate
   *   }
   * })
   * 
   */
  create<T extends MaterialRateCreateArgs>(args: Prisma.SelectSubset<T, MaterialRateCreateArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MaterialRates.
   * @param {MaterialRateCreateManyArgs} args - Arguments to create many MaterialRates.
   * @example
   * // Create many MaterialRates
   * const materialRate = await prisma.materialRate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaterialRateCreateManyArgs>(args?: Prisma.SelectSubset<T, MaterialRateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MaterialRates and returns the data saved in the database.
   * @param {MaterialRateCreateManyAndReturnArgs} args - Arguments to create many MaterialRates.
   * @example
   * // Create many MaterialRates
   * const materialRate = await prisma.materialRate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MaterialRates and only return the `id`
   * const materialRateWithIdOnly = await prisma.materialRate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MaterialRateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MaterialRateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MaterialRate.
   * @param {MaterialRateDeleteArgs} args - Arguments to delete one MaterialRate.
   * @example
   * // Delete one MaterialRate
   * const MaterialRate = await prisma.materialRate.delete({
   *   where: {
   *     // ... filter to delete one MaterialRate
   *   }
   * })
   * 
   */
  delete<T extends MaterialRateDeleteArgs>(args: Prisma.SelectSubset<T, MaterialRateDeleteArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MaterialRate.
   * @param {MaterialRateUpdateArgs} args - Arguments to update one MaterialRate.
   * @example
   * // Update one MaterialRate
   * const materialRate = await prisma.materialRate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaterialRateUpdateArgs>(args: Prisma.SelectSubset<T, MaterialRateUpdateArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MaterialRates.
   * @param {MaterialRateDeleteManyArgs} args - Arguments to filter MaterialRates to delete.
   * @example
   * // Delete a few MaterialRates
   * const { count } = await prisma.materialRate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaterialRateDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaterialRateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaterialRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialRateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MaterialRates
   * const materialRate = await prisma.materialRate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaterialRateUpdateManyArgs>(args: Prisma.SelectSubset<T, MaterialRateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaterialRates and returns the data updated in the database.
   * @param {MaterialRateUpdateManyAndReturnArgs} args - Arguments to update many MaterialRates.
   * @example
   * // Update many MaterialRates
   * const materialRate = await prisma.materialRate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MaterialRates and only return the `id`
   * const materialRateWithIdOnly = await prisma.materialRate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MaterialRateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MaterialRateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MaterialRate.
   * @param {MaterialRateUpsertArgs} args - Arguments to update or create a MaterialRate.
   * @example
   * // Update or create a MaterialRate
   * const materialRate = await prisma.materialRate.upsert({
   *   create: {
   *     // ... data to create a MaterialRate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MaterialRate we want to update
   *   }
   * })
   */
  upsert<T extends MaterialRateUpsertArgs>(args: Prisma.SelectSubset<T, MaterialRateUpsertArgs<ExtArgs>>): Prisma.Prisma__MaterialRateClient<runtime.Types.Result.GetResult<Prisma.$MaterialRatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MaterialRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialRateCountArgs} args - Arguments to filter MaterialRates to count.
   * @example
   * // Count the number of MaterialRates
   * const count = await prisma.materialRate.count({
   *   where: {
   *     // ... the filter for the MaterialRates we want to count
   *   }
   * })
  **/
  count<T extends MaterialRateCountArgs>(
    args?: Prisma.Subset<T, MaterialRateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaterialRateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MaterialRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialRateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaterialRateAggregateArgs>(args: Prisma.Subset<T, MaterialRateAggregateArgs>): Prisma.PrismaPromise<GetMaterialRateAggregateType<T>>

  /**
   * Group by MaterialRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialRateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaterialRateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaterialRateGroupByArgs['orderBy'] }
      : { orderBy?: MaterialRateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaterialRateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaterialRateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MaterialRate model
 */
readonly fields: MaterialRateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MaterialRate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaterialRateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MaterialRate model
 */
export interface MaterialRateFieldRefs {
  readonly id: Prisma.FieldRef<"MaterialRate", 'String'>
  readonly materialType: Prisma.FieldRef<"MaterialRate", 'String'>
  readonly unit: Prisma.FieldRef<"MaterialRate", 'String'>
  readonly rate: Prisma.FieldRef<"MaterialRate", 'Float'>
  readonly currency: Prisma.FieldRef<"MaterialRate", 'String'>
  readonly source: Prisma.FieldRef<"MaterialRate", 'String'>
  readonly updatedAt: Prisma.FieldRef<"MaterialRate", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MaterialRate findUnique
 */
export type MaterialRateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * Filter, which MaterialRate to fetch.
   */
  where: Prisma.MaterialRateWhereUniqueInput
}

/**
 * MaterialRate findUniqueOrThrow
 */
export type MaterialRateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * Filter, which MaterialRate to fetch.
   */
  where: Prisma.MaterialRateWhereUniqueInput
}

/**
 * MaterialRate findFirst
 */
export type MaterialRateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * Filter, which MaterialRate to fetch.
   */
  where?: Prisma.MaterialRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialRates to fetch.
   */
  orderBy?: Prisma.MaterialRateOrderByWithRelationInput | Prisma.MaterialRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaterialRates.
   */
  cursor?: Prisma.MaterialRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaterialRates.
   */
  distinct?: Prisma.MaterialRateScalarFieldEnum | Prisma.MaterialRateScalarFieldEnum[]
}

/**
 * MaterialRate findFirstOrThrow
 */
export type MaterialRateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * Filter, which MaterialRate to fetch.
   */
  where?: Prisma.MaterialRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialRates to fetch.
   */
  orderBy?: Prisma.MaterialRateOrderByWithRelationInput | Prisma.MaterialRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaterialRates.
   */
  cursor?: Prisma.MaterialRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaterialRates.
   */
  distinct?: Prisma.MaterialRateScalarFieldEnum | Prisma.MaterialRateScalarFieldEnum[]
}

/**
 * MaterialRate findMany
 */
export type MaterialRateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * Filter, which MaterialRates to fetch.
   */
  where?: Prisma.MaterialRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialRates to fetch.
   */
  orderBy?: Prisma.MaterialRateOrderByWithRelationInput | Prisma.MaterialRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MaterialRates.
   */
  cursor?: Prisma.MaterialRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialRates.
   */
  skip?: number
  distinct?: Prisma.MaterialRateScalarFieldEnum | Prisma.MaterialRateScalarFieldEnum[]
}

/**
 * MaterialRate create
 */
export type MaterialRateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * The data needed to create a MaterialRate.
   */
  data: Prisma.XOR<Prisma.MaterialRateCreateInput, Prisma.MaterialRateUncheckedCreateInput>
}

/**
 * MaterialRate createMany
 */
export type MaterialRateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MaterialRates.
   */
  data: Prisma.MaterialRateCreateManyInput | Prisma.MaterialRateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MaterialRate createManyAndReturn
 */
export type MaterialRateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * The data used to create many MaterialRates.
   */
  data: Prisma.MaterialRateCreateManyInput | Prisma.MaterialRateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MaterialRate update
 */
export type MaterialRateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * The data needed to update a MaterialRate.
   */
  data: Prisma.XOR<Prisma.MaterialRateUpdateInput, Prisma.MaterialRateUncheckedUpdateInput>
  /**
   * Choose, which MaterialRate to update.
   */
  where: Prisma.MaterialRateWhereUniqueInput
}

/**
 * MaterialRate updateMany
 */
export type MaterialRateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MaterialRates.
   */
  data: Prisma.XOR<Prisma.MaterialRateUpdateManyMutationInput, Prisma.MaterialRateUncheckedUpdateManyInput>
  /**
   * Filter which MaterialRates to update
   */
  where?: Prisma.MaterialRateWhereInput
  /**
   * Limit how many MaterialRates to update.
   */
  limit?: number
}

/**
 * MaterialRate updateManyAndReturn
 */
export type MaterialRateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * The data used to update MaterialRates.
   */
  data: Prisma.XOR<Prisma.MaterialRateUpdateManyMutationInput, Prisma.MaterialRateUncheckedUpdateManyInput>
  /**
   * Filter which MaterialRates to update
   */
  where?: Prisma.MaterialRateWhereInput
  /**
   * Limit how many MaterialRates to update.
   */
  limit?: number
}

/**
 * MaterialRate upsert
 */
export type MaterialRateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * The filter to search for the MaterialRate to update in case it exists.
   */
  where: Prisma.MaterialRateWhereUniqueInput
  /**
   * In case the MaterialRate found by the `where` argument doesn't exist, create a new MaterialRate with this data.
   */
  create: Prisma.XOR<Prisma.MaterialRateCreateInput, Prisma.MaterialRateUncheckedCreateInput>
  /**
   * In case the MaterialRate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaterialRateUpdateInput, Prisma.MaterialRateUncheckedUpdateInput>
}

/**
 * MaterialRate delete
 */
export type MaterialRateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
  /**
   * Filter which MaterialRate to delete.
   */
  where: Prisma.MaterialRateWhereUniqueInput
}

/**
 * MaterialRate deleteMany
 */
export type MaterialRateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaterialRates to delete
   */
  where?: Prisma.MaterialRateWhereInput
  /**
   * Limit how many MaterialRates to delete.
   */
  limit?: number
}

/**
 * MaterialRate without action
 */
export type MaterialRateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialRate
   */
  select?: Prisma.MaterialRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialRate
   */
  omit?: Prisma.MaterialRateOmit<ExtArgs> | null
}
